export const ActionTypes = {
  LOAD_FILES: "LOAD_FILES",
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
  SET_CURRENT_TIME: "SET_CURRENT_TIME",
  SET_DURATION: "SET_DURATION",
  SET_INDEX: "SET_INDEX",
  SET_IS_PLAYING: "SET_IS_PLAYING",
  SET_MUTED: "SET_MUTED",
  STOP: "STOP",
  TOGGLE_MUTED: "TOGGLE_MUTED",
  TOGGLE_PLAY: "TOGGLE_PLAY",
  UPDATE_MEDIA_INFO: "UPDATE_MEDIA_INFO",
} as const;
